#MARTe2 Debian Training Docker Image
FROM debian:latest

LABEL maintainer="Bernardo Carvalho <bernardo.carvalho@tecnico.ulisboa.pt>"

#Setting path for workdir
ARG WORK_PATH=~/Projects
#Setting workdir
WORKDIR $WORK_PATH
#Installing all the dependencies needed
RUN apt-get -y update
RUN apt-get -y install zsh curl git tmux python3-pip  python3-pyqt6 libqt6sql6-mysql
RUN apt-get -y install build-essential cmake python3-reportlab python3-pyqtgraph python3-pandas
RUN apt-get -y install libncurses-dev libxml2 libreadline-dev
# Clear Cache
RUN rm -rf /var/lib/apt/lists/*
RUN curl -fsSL http://www.mdsplus.org/dist/mdsplus.gpg.key | tee /etc/apt/trusted.gpg.d/mdsplus.asc > /dev/null
RUN echo 'deb [arch=amd64] http://www.mdsplus.org/dist/debian/bullseye/repo MDSplus alpha' > /etc/apt/sources.list.d/mdsplus.list
RUN apt-get update

RUN apt-get -y install mdsplus-alpha-kernel mdsplus-alpha-python
RUN curl -L git.io/antigen > /root/antigen.zsh
COPY zshrc-antigen.sh /root/.zshrc
# Getting EPICS
RUN cd /opt && git clone --recursive https://github.com/epics-base/epics-base.git
# Compiling EPICS
# RUN cd /opt/epics-base && echo "OP_SYS_CXXFLAGS += -std=c++11" >> configure/os/CONFIG_SITE.linux-x86_64.Common
RUN cd /opt/epics-base && make
# Environment variables
ENV MARTe2_DIR=/opt/MARTe2-dev
ENV MARTe2_Components_DIR=/opt/MARTe2-components
ENV EPICS_BASE=/opt/epics-base
ENV EPICSPVA=/opt/epics-base
ENV EPICS_HOST_ARCH=linux-x86_64
ENV MDSPLUS_DIR=/usr/local/mdsplus
ENV PATH=$PATH:/opt/epics-base/bin/linux-x86_64
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MARTe2_DIR/Build/x86-linux/Core/:$EPICS_BASE/lib/$EPICS_HOST_ARCH
# Compiling MARTe2
# RUN mkdir /root/Projects
RUN cd /opt && git clone https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2.git MARTe2-dev
#RUN cd $MARTe2_DIR && make -f Makefile.linux
RUN cd /opt && git clone https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2-components.git
#RUN cd $MARTe2_Components_DIR && make -f Makefile.linux
# RUN cd /root/Projects/MARTe2-components && make -f Makefile.linux
# RUN cd /root/Projects && git clone https://github.com/bernardocarvalho/MARTe2-demos-padova.git
RUN /usr/bin/zsh /root/.zshrc
# RUN cd /root/Projects/MARTe2-demos-padova && git checkout isttok-marte && make -f Makefile.x86-linux

# syntax=docker/dockerfile:1
